name: Deploy Container

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build Lambda
        run: |
          cd Lambda
          sam build -m requirements.txt --use-container
      - name: Deploy Terraform
        run: |
          cd Terraform
          terraform init
          terraform plan -out=lambda.plan
          terraform apply lambda.plan
