name: Test PR

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

jobs:
  test-lambda:
    name: Test Lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Lambda

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build Lambda
        run: |
          sam build -m requirements.txt --use-container
          make test

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: Terraform

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"
      - name: Validate Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform validate
    
